cc_library(
    name = "Base",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"] + [
        "Dev/BuildConfig.h",
        "Profile/BuildConfig.h",
        "Release/BuildConfig.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
    ],
)
