cc_library(
    name = "Ultra",
    hdrs = [
        "ultra_R4300.h",
        "ultra_abi.h",
        "ultra_gbi.h",
        "ultra_mbi.h",
        "ultra_os.h",
        "ultra_rcp.h",
        "ultra_sptask.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//Base",
    ],
)
