cc_library(
    name = "BatchTest",
    srcs = ["BatchTest.cpp"],
    hdrs = ["BatchTest.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//Base",
        "//Core",
        "//Debug",
        "//HLEGraphics",
        "//RomFile",
        "//System:SystemInit",
        "//Utility",
    ],
)

cc_library(
    name = "TestUtil",
    srcs = ["TestUtil.cpp"],
    hdrs = ["TestUtil.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//Base",
        "@com_google_absl//absl/strings",
    ],
)
