# Abseil.
http_archive(
    name = "com_google_absl",
    url = "https://github.com/abseil/abseil-cpp/archive/master.zip",
    strip_prefix = "abseil-cpp-master",
)

# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
     name = "com_google_googletest",
     urls = ["https://github.com/google/googletest/archive/master.zip"],
     strip_prefix = "googletest-master",
)
