workspace(name = "daedalus")

# Abseil.
http_archive(
    name = "com_google_absl",
    url = "https://github.com/abseil/abseil-cpp/archive/master.zip",
    strip_prefix = "abseil-cpp-master",
)

# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
    name = "com_google_googletest",
    url = "https://github.com/google/googletest/archive/master.zip",
    strip_prefix = "googletest-master",
)

new_http_archive(
    name = "glfw",
    url = "https://github.com/glfw/glfw/archive/master.zip",
    strip_prefix = "glfw-master",
    build_file = "BUILD.glfw",
)

new_http_archive(
    name = "webby",
    url = "https://github.com/deplinenoise/webby/archive/master.zip",
    strip_prefix = "webby-master",
    build_file = "BUILD.webby",
)
