cc_library(
    name = "OSHLE",
    srcs = glob(["*.cpp"]),
    hdrs = glob([
        "*.h",
        "*.inl",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//Base",
        "//Config",
        "//Core",
        "//Debug",
        "//DynaRec",
        "//Math",
        "//Plugins",
        "//Utility",
    ],
)
